# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qmodels import MyMessageBox

class AddPopup(QtWidgets.QWidget):
    Args = QtCore.pyqtSignal(list)

    def __init__(self, parent:QtWidgets.QWidget=None , ext:bool=False):
        super().__init__(parent)
        self.setObjectName("AddPopup")
        self.resize(340, 170)
        self.ext = ext
        self.msg = MyMessageBox(self)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameLabel = QtWidgets.QLabel(self.frame)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel, 0, QtCore.Qt.AlignHCenter)
        self.nameLabel.setText("Name : ")
        self.nameedit = QtWidgets.QLineEdit(self.frame)
        self.nameedit.setObjectName("nameedit")
        self.horizontalLayout.addWidget(self.nameedit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.frame)
        if ext :
            self.frame_3 = QtWidgets.QFrame(self)
            self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
            self.frame_3.setObjectName("frame_3")
            self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
            self.horizontalLayout_2.setObjectName("horizontalLayout_2")
            self.extensionLabel = QtWidgets.QLabel(self.frame_3)
            self.extensionLabel.setObjectName("extensionLabel")
            self.extensionLabel.setText("Extention : ")
            self.horizontalLayout_2.addWidget(self.extensionLabel, 0, QtCore.Qt.AlignHCenter)
            self.extensionedit = QtWidgets.QLineEdit(self.frame_3)
            self.extensionedit.setObjectName("extensionedit")
            self.horizontalLayout_2.addWidget(self.extensionedit)
            self.horizontalLayout_2.setStretch(0, 1)
            self.horizontalLayout_2.setStretch(1, 2)
            self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.okBtn = QtWidgets.QToolButton(self.frame_2)
        self.okBtn.setObjectName("okBtn")
        self.okBtn.setIcon(QtGui.QIcon("assets\icons\ok.png"))
        self.okBtn.setFixedSize(50,50)
        self.okBtn.setIconSize(QtCore.QSize(30,30))
        self.horizontalLayout_3.addWidget(self.okBtn)
        self.cancelBtn = QtWidgets.QToolButton(self.frame_2)
        self.cancelBtn.setObjectName("cancelBtn")
        self.cancelBtn.setIcon(QtGui.QIcon("assets\icons\cancel.png"))
        self.cancelBtn.setFixedSize(50,50)
        self.cancelBtn.setIconSize(QtCore.QSize(30,30))
        self.cancelBtn.clicked.connect(self.close)
        self.horizontalLayout_3.addWidget(self.cancelBtn)
        self.verticalLayout.addWidget(self.frame_2)

    def ok (self):
        name = self.nameedit.text()
        args = []
        if self.validate(name):
            args.append(name)
            try :
                args.append(self.extensionedit.text()) 
            except :...
            self.Args.emit([name])
            self.close()
        else :
            self.msg.showWarning("Not Valid","Please enter name with length more than or equal 3 letters ")

    def validate(self,text:str)->bool:
        return len(text) >= 3 



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = AddPopup()
    ui.show()
    sys.exit(app.exec_())
