# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qmodels import Calendar

class ReportPage(QtWidgets.QWidget):
    def __init__(self, parent:QtWidgets.QWidget=None):
        super().__init__(parent)
        self.setObjectName("ReportPage")
        self.resize(783, 607)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.statusbox = QtWidgets.QComboBox(self.frame)
        self.statusbox.setObjectName("statusbox")
        self.horizontalLayout_2.addWidget(self.statusbox)
        self.agentbox = QtWidgets.QComboBox(self.frame)
        self.agentbox.setObjectName("agentbox")
        self.horizontalLayout_2.addWidget(self.agentbox)
        self.projectbox = QtWidgets.QComboBox(self.frame)
        self.projectbox.setObjectName("projectbox")
        self.horizontalLayout_2.addWidget(self.projectbox)
        self.sourcebox = QtWidgets.QComboBox(self.frame)
        self.sourcebox.setObjectName("sourcebox")
        self.horizontalLayout_2.addWidget(self.sourcebox)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.calenderBtn = QtWidgets.QToolButton(self.frame_4)
        self.calenderBtn.setObjectName("calenderBtn")
        self.calenderLabel = QtWidgets.QLabel(self.frame_4)
        self.horizontalLayout_4.addWidget(self.calenderBtn , alignment=QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_4.addWidget(self.calenderLabel , alignment=QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.frame_2)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.counterLabel = QtWidgets.QLabel(self.frame_2)
        self.counterLabel.setObjectName("counterLabel")
        self.verticalLayout.addWidget(self.counterLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exportBtn = QtWidgets.QToolButton(self.frame_3)
        self.exportBtn.setObjectName("exportBtn")
        self.horizontalLayout_3.addWidget(self.exportBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.signture = QtWidgets.QLabel(self.frame_3)
        self.signture.setObjectName("signture")
        self.horizontalLayout_3.addWidget(self.signture, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 5)
        self.horizontalLayout.addWidget(self.widget)

        self.sourcebox.setFixedHeight(40)
        self.agentbox.setFixedHeight(40)
        self.projectbox.setFixedHeight(40)
        self.statusbox.setFixedHeight(40)

        self.calenderBtn.setIcon(QtGui.QIcon("assets\icons\calendar.png"))
        self.calenderBtn.setFixedSize(50,50)
        self.calenderBtn.setIconSize(QtCore.QSize(30,30))

        self.exportBtn.setIcon(QtGui.QIcon("assets\icons\export.png"))
        self.exportBtn.setFixedSize(50,50)
        self.exportBtn.setIconSize(QtCore.QSize(30,30))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setPointSize(10)
        font.setFamily("Narkisim")
        self.signture.setFont(font)
        self.signture.setObjectName("signture")
        self.signture.setText("MarCode")

        self.calendarwidget = Calendar()
        self.calenderBtn.clicked.connect(self.calendarwidget.show)







if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = ReportPage()
    ui.show()
    sys.exit(app.exec_())
